# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
        db_provider:
            entity:
                class: BenProjectBundle:User
                property: username

        in_memory:
            memory: ~

    encoders:
        BenProjectBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
